######################################################################
#
# File name : tb_lcd_rgb_char_wave.do
# Created on: Wed Jun 21 11:05:20 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
