######################################################################
#
# File name : tb_lcd_rgb_char.udo
# Created on: Wed Jun 21 11:05:20 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
