######################################################################
#
# File name : tb_lcd_rgb_colorbar_simulate.do
# Created on: Sun Jun 25 15:04:24 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_lcd_rgb_colorbar xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_lcd_rgb_colorbar_wave.do}

view wave
view structure
view signals

do {tb_lcd_rgb_colorbar.udo}

run 1000ns
