######################################################################
#
# File name : tb_lcd_rgb_colorbar.udo
# Created on: Sun Jun 25 15:04:24 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
