######################################################################
#
# File name : tb_lcd_rgb_colorbar_compile.do
# Created on: Sun Jun 25 15:04:22 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../../rtl/clk_div.v" \
"../../../../../rtl/lcd_display.v" \
"../../../../../rtl/lcd_driver.v" \
"../../../../../rtl/lcd_rgb_colorbar.v" \
"../../../../../rtl/rd_id.v" \
"../../../../../sim/tb_lcd_rgb_colorbar.v" \


# compile glbl module
C:\\modeltech64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

