######################################################################
#
# File name : tb_lcd_rgb_colorbar_wave.do
# Created on: Sun Jun 25 15:04:24 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
